version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      day: friday
