[versions]
# libraries
junit5 = "6.1.2"
junit4 = "4.13.2"

# plugins
versions = "0.54.0"

[libraries]
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit5" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
junit-vintage = { group = "org.junit.vintage", name = "junit-vintage-engine" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
